[tools]
bat = "latest"
bat-extras = "latest"
bun = "latest"
claude = "latest"
delta = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
jj = "latest"
jqp = "latest"
lazygit = "latest"
neovim = "latest"
node = "22"
python = "3.14"
ripgrep = "latest"
starship = "latest"
terraform = "latest"
uv = "latest"
xh = "latest"
yq = "latest"

[settings]
experimental = true
lockfile = true
